name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify the Node.js version you want to use
    - name: Install dependencies
      run: npm i

    - name: Run Cypress tests
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        record-html: true
        video: true
        wait-on: 'http://localhost:3000'
        start: npm run cypress:open
        args: run
